### ISSUE TITLE
CLI changes for Sunrise initiative

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1487]
```[tasklist]
### Tasks
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1513
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1512
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1514
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1515
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1516
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1517
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1518
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1519
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1520
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1509
- [ ] https://github.com/graphprotocol/graph-tooling/issues/1532
```

**Comment by azf20** [comment]
@saihaj for `graph create` I think this would also need to be added as a `graph local` subcommand
